import type { Transaction } from "@/types/analytics";

/**
 * Mock transaction data for the analytics dashboard.
 * In production this would be fetched from the Mux Protocol API.
 */
export const mockTransactions: Transaction[] = [
	{
		id: "1",
		description: "Spotify Premium",
		date: "2023-10-24",
		humanDate: "Oct 24, 2023",
		category: "Subscription",
		status: "completed",
		amount: 15.99,
		currency: "USD",
		type: "outgoing",
	},
	{
		id: "2",
		description: "Design Project #4",
		date: "2023-10-23",
		humanDate: "Oct 23, 2023",
		category: "Income",
		status: "completed",
		amount: 1250.0,
		currency: "USD",
		type: "incoming",
	},
	{
		id: "3",
		description: "Uber Ride",
		date: "2023-10-22",
		humanDate: "Oct 22, 2023",
		category: "Transport",
		status: "pending",
		amount: 24.5,
		currency: "USD",
		type: "outgoing",
	},
	{
		id: "4",
		description: "Whole Foods Market",
		date: "2023-10-21",
		humanDate: "Oct 21, 2023",
		category: "Groceries",
		status: "completed",
		amount: 142.8,
		currency: "USD",
		type: "outgoing",
	},
	{
		id: "5",
		description: "ATM Withdrawal",
		date: "2023-10-20",
		humanDate: "Oct 20, 2023",
		category: "Cash",
		status: "failed",
		amount: 200.0,
		currency: "USD",
		type: "outgoing",
	},
	{
		id: "6",
		description: "Refund: Amazon",
		date: "2023-10-19",
		humanDate: "Oct 19, 2023",
		category: "Shopping",
		status: "completed",
		amount: 45.0,
		currency: "USD",
		type: "incoming",
	},
	{
		id: "7",
		description: "Electric Bill",
		date: "2023-10-18",
		humanDate: "Oct 18, 2023",
		category: "Utilities",
		status: "completed",
		amount: 95.2,
		currency: "USD",
		type: "outgoing",
	},
	{
		id: "8",
		description: "Netflix",
		date: "2023-10-17",
		humanDate: "Oct 17, 2023",
		category: "Subscription",
		status: "completed",
		amount: 12.99,
		currency: "USD",
		type: "outgoing",
	},
	{
		id: "9",
		description: "Upwork Payout",
		date: "2023-10-16",
		humanDate: "Oct 16, 2023",
		category: "Income",
		status: "completed",
		amount: 850.0,
		currency: "USD",
		type: "incoming",
	},
	{
		id: "10",
		description: "Coffee Shop",
		date: "2023-10-15",
		humanDate: "Oct 15, 2023",
		category: "Food",
		status: "pending",
		amount: 6.5,
		currency: "USD",
		type: "outgoing",
	},
	{
		id: "11",
		description: "Gym Membership",
		date: "2023-10-14",
		humanDate: "Oct 14, 2023",
		category: "Health",
		status: "completed",
		amount: 45.0,
		currency: "USD",
		type: "outgoing",
	},
	{
		id: "12",
		description: "Apple Store",
		date: "2023-10-13",
		humanDate: "Oct 13, 2023",
		category: "Tech",
		status: "failed",
		amount: 1299.0,
		currency: "USD",
		type: "outgoing",
	},
];
